import type { Metadata } from 'next';
import { resolveAnalysis } from '@/lib/github/provider';
import { extractUsername } from '@/lib/github/client';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { Logo } from '@/components/ui/Logo';
import { Button } from '@/components/ui/Button';
import { ShareCard } from '@/components/dashboard/ShareCard';

export const dynamic = 'force-dynamic';

export async function generateMetadata({ params }: { params: { username: string } }): Promise<Metadata> {
  const uname = extractUsername(params.username) ?? params.username;
  return {
    title: `${uname} — DevLens Profile`,
    description: `Developer intelligence card for ${uname}, generated by DevLens.`,
    openGraph: {
      title: `${uname} · DevLens`,
      description: 'Developer Intelligence — measured activity, projects, collaboration and growth.',
    },
  };
}

export default async function SharePage({ params }: { params: { username: string } }) {
  const uname = extractUsername(params.username) ?? params.username;
  let report;
  try {
    const res = await resolveAnalysis(uname);
    report = res.report;
  } catch {
    notFound();
  }

  return (
    <div className="flex min-h-screen flex-col bg-canva">
      <header className="mx-auto flex w-full max-w-3xl items-center justify-between px-5 py-5">
        <Link href="/"><Logo /></Link>
        <Button variant="ghost" size="sm">
          <Link href="/">New analysis</Link>
        </Button>
      </header>
      <main className="mx-auto flex w-full max-w-3xl flex-1 flex-col items-center justify-center px-5 py-10">
        <div className="animate-slide-up">
          <ShareCard report={report} />
        </div>
        <p className="mt-6 max-w-md text-center text-xs leading-relaxed text-muted">
          This card summarizes measured public GitHub signals: activity, project health,
          technology mix, collaboration and growth. It is a directional snapshot, not a
          verdict on overall developer quality.
        </p>
      </main>
      <footer className="border-t border-borderline py-5 text-center text-xs text-muted">
        Generated with DevLens · Developer Intelligence Platform
      </footer>
    </div>
  );
}